tbNameResWeapon = {
	[1] = {
		szName = "TriÒn Thñ",
		tbEquip = {
			{"B¹ch Hæ Phæ TÕ TriÒn Thñ",44},
			{"B¹ch Hæ Hµn Ngäc TriÒn Thñ",45},
			{"B¹ch Hæ §éc Sa TriÒn Thñ",46},
			{"B¹ch Hæ Hé Ph¸p TriÒn Thñ",47},
			{"Minh Ph­îng Quy Y TriÒn Thñ",84},
			{"Minh Ph­îng L¨ng Tiªu TriÒn Thñ",91},
			{"Minh Ph­îng Diªm La TriÒn Thñ",94},
			{"Minh Ph­îng ThiÕt HuyÕt TriÒn Thñ",99},
			{"§»ng Long Bå §Ò TriÒn Thñ",110},
			{"§»ng Long B¨ng Ph¸ch TriÒn Thñ",117},
			{"§»ng Long V¹n §éc TriÒn Thñ",120},
			{"§»ng Long Hµo T×nh TriÒn Thñ",125},
			{"Tinh S­¬ng-Khæ §Õ TriÒn Thñ",135},
			{"Tinh S­¬ng-PhÊt HuyÖt TriÒn Thñ",142},
			{"Tinh S­¬ng-ThiÒm Phi TriÒn Thñ",145},
			{"Tinh S­¬ng-M·nh Long TriÒn Thñ",150},
			{"NguyÖt KhuyÕt Träng KiÕp TriÒn Thñ",160},
			{"NguyÖt KhuyÕt HiÓu NguyÖt TriÒn Thñ",167},
			{"NguyÖt KhuyÕt B¸ch §éc TriÒn Thñ",170},
			{"NguyÖt KhuyÕt XÝch Long TriÒn Thñ",175},
			{"DiÖu D­¬ng Méng Long TriÒn Thñ",185},
			{"DiÖu D­¬ng V« Ma TriÒn Thñ",192},
			{"DiÖu D­¬ng U Lung TriÒn Thñ",195},
			{"DiÖu D­¬ng §ång Cõu TriÒn Thñ",200},
			{"Anh Hµo La H¸n TriÒn Thñ",220},
			{"Anh Hµo TuyÕt S¾c TriÒn Thñ",227},
			{"Anh Hµo Ban Lan TriÒn Thñ",230},
			{"Anh Hµo Tr­êng Phong TriÒn Thñ",235},
		}
	},
	[2] = {
		szName = "KiÕm",
		tbEquip = {
			{"Thanh C©u V« S¾c Tr­êng KiÕm",3},
			{"N÷ Oa Hµn T­¬ng",20},
			{"V« Gian û Thiªn KiÕm",21},
			{"Tö M·ng XuÊt TrÇn KiÕm",36},
			{"Tö M·ng Ch©n Viªn KiÕm",37},
			{"B¹ch Hæ L­u V©n Tr­êng KiÕm",57},
			{"B¹ch Hæ Tiªn ¢m KiÕm",58},
			{"B¹ch Hæ Ng¹o S­¬ng Tr­êng KiÕm",59},
			{"Minh Ph­îng T¶n Hoa Tr­êng KiÕm",90},
			{"Minh Ph­îng Kh«ng Minh KiÕm",103},
			{"Minh Ph­îng Bång Lai KiÕm",104},
			{"Minh Ph­îng Tham Th­¬ng KiÕm",106},
			{"Tö M·ng §«ng Li KiÕm",107},
			{"B¹ch Hæ Qu©n Cè KiÕm",108},
			{"Minh Ph­îng ¤ Ngäc KiÕm",109},
			{"§»ng Long Phi Thiªn B¶o KiÕm",116},
			{"§»ng Long Ngäc H­ ThÇn KiÕm",129},
			{"§»ng Long HuyÒn Thiªn ThÇn KiÕm",130},
			{"§»ng Long Th­¬ng Khung ThÇn KiÕm",132},
			{"§»ng Long Tè Du KiÕm",133},
			{"§»ng Long Y Thñy KiÕm",134},
			{"Tinh S­¬ng-L¹c Anh B¶o KiÕm",141},
			{"Tinh S­¬ng-ChÊn S¬n ThÇn KiÕm",154},
			{"Tinh S­¬ng-Qu©n Uy ThÇn KiÕm",155},
			{"Tinh S­¬ng-Oanh Minh ThÇn KiÕm",157},
			{"Tinh S­¬ng-H¹o Thiªn KiÕm",158},
			{"Tinh S­¬ng-Thanh H­ KiÕm",159},
			{"NguyÖt KhuyÕt Kinh Hång B¶o KiÕm",166},
			{"NguyÖt KhuyÕt Linh §éng ThÇn KiÕm",179},
			{"NguyÖt KhuyÕt ¶o ¶nh ThÇn KiÕm",180},
			{"NguyÖt KhuyÕt Méc Vò ThÇn KiÕm",182},
			{"NguyÖt KhuyÕt DËt ¶nh KiÕm",183},
			{"NguyÖt KhuyÕt Thanh Phong KiÕm",184},
			{"DiÖu D­¬ng V« Gian B¶o KiÕm",191},
			{"DiÖu D­¬ng L¨ng Nh¹c ThÇn KiÕm",204},
			{"DiÖu D­¬ng CËp Phong ThÇn KiÕm",205},
			{"DiÖu D­¬ng L«i Khung ThÇn KiÕm",207},
			{"DiÖu D­¬ng Phï V©n KiÕm",208},
			{"DiÖu D­¬ng Xung V©n KiÕm",209},
			{"Anh Hµo V« S¾c Tr­êng KiÕm",226},
			{"Anh Hµo Th¸i Cùc KiÕm",239},
			{"Anh Hµo Linh Ch©n KiÕm",240},
			{"Anh Hµo Tö §iÖn KiÕm",242},
			{"Anh Hµo Th­¬ng Lan KiÕm",243},
			{"Anh Hµo BÝch Hoa KiÕm",244},
			{"Thanh C©u Chi B¸t MÆc KiÕm",247},
			{"Kim ¤ Chi Nhu V©n KiÕm",248},
			{"NguyÖt KhuyÕt Chi Xung Linh KiÕm",249},
			{"Anh Hµo Chi Hoa Èn KiÕm",250},
		}
	},
	[3] = {
		szName = "§ao",
		tbEquip = {
			{"B¹ch Hæ S¸t Viªm §ao",55},
			{"Anh Hµo B¹ch Hång §ao",241},
			{"Thanh C©u Kim C­¬ng Giíi §ao",6},
			{"Phôc Hi To¸i T©m",22},
			{"Tø Kh«ng Gi¸ng Ma Giíi ®ao",23},
			{"Tö M·ng Thanh TÞnh Giíi §ao",32},
			{"Tö M·ng Thanh S­¬ng §ao",33},
			{"Tö M·ng Xuyªn T©m §ao",34},
			{"Tö M·ng §o¹n Thñy §ao",35},
			{"B¹ch Hæ Ma Ni Giíi §ao",52},
			{"B¹ch Hæ U Linh B¶o §ao",53},
			{"B¹ch Hæ Hång Nhan B¶o §ao",54},
			{"B¹ch Hæ Thiªn Canh B¶o §ao",56},
			{"Minh Ph­îng H­ Kh«ng Giíi §ao",86},
			{"Minh Ph­îng B¸ V­¬ng B¶o §ao",89},
			{"Minh Ph­îng V¹n Hoa B¶o §ao",92},
			{"Minh Ph­îng Minh V­¬ng B¶o §ao",95},
			{"Minh Ph­îng SÝ §Þa §ao",102},
			{"Minh Ph­îng Cöu Thiªn Hµn ThiÕt",105},
			{"§»ng Long V« L­îng Giíi §ao",112},
			{"§»ng Long Hçn Nguyªn B¶o §ao",115},
			{"§»ng Long Khuynh Thµnh B¶o §ao",118},
			{"§»ng Long V¹n Linh HuyÕt NhÉn",121},
			{"§»ng Long PhÇn Thiªn B¶o §ao",128},
			{"§»ng Long Ph­¬ng Nguyªn B¶o §ao",131},
			{"Tinh S­¬ng-§¹o §Õ Giíi §ao",137},
			{"Tinh S­¬ng-L÷ S­¬ng B¶o §ao",140},
			{"Tinh S­¬ng-Thiªn H­¬ng B¶o §ao",143},
			{"Tinh S­¬ng-Phô Cèt HuyÕt NhËn",146},
			{"Tinh S­¬ng-Khèc Viªm B¶o §ao",153},
			{"Tinh S­¬ng-Minh L«i B¶o §ao",156},
			{"NguyÖt KhuyÕt Ph¸ KiÕp Giíi §ao",162},
			{"NguyÖt KhuyÕt Tr­êng Kh«ng B¶o §ao",165},
			{"NguyÖt KhuyÕt T­¬ng T­ B¶o §ao",168},
			{"NguyÖt KhuyÕt U Minh HuyÕt NhÉn",171},
			{"NguyÖt KhuyÕt LiÖt D­¬ng B¶o §ao",178},
			{"NguyÖt KhuyÕt L¨ng Phong B¶o §ao",181},
			{"DiÖu D­¬ng T­ Kh«ng Giíi §ao",187},
			{"DiÖu D­¬ng Ngù Long B¶o §ao",190},
			{"DiÖu D­¬ng Tª Hoµng B¶o §ao",193},
			{"DiÖu D­¬ng Minh ¶o HuyÕt NhËn",196},
			{"DiÖu D­¬ng Ma Hoµng B¶o §ao",203},
			{"DiÖu D­¬ng S­¬ng Tinh B¶o §ao",206},
			{"Anh Hµo Kim Cang Giíi §ao",222},
			{"Anh Hµo §¹i Lùc B¶o §ao",225},
			{"Anh Hµo Tè La §ao",228},
			{"Anh Hµo Lôc Quang §éc NhËn",231},
			{"Anh Hµo NghiÖp Háa §ao",238},
		}
	},
	[4] = {
		szName = "Th­¬ng",
		tbEquip = {
			{"Thanh C©u Liªn Hoa Tr­îng",11},
			{"Thanh C©u PhËt §µ T¨ng C«n",12},
			{"V©n Léc Giíi LuËt T¨ng C«n",26},
			{"Phôc Ma Tö Kim C«n",27},
			{"Tö M·ng Tø Kh«ng T¨ng C«n",40},
			{"Tö M·ng Háa V©n Tr­îng",41},
			{"Minh Ph­îng Cùc L¹c T¨ng C«n",85},
			{"Minh Ph­îng Quang Phôc Tr­îng",100},
			{"§»ng Long Nh­ Lai Ph¸p C«n",111},
			{"§»ng Long Tô NghÜa Tr­îng",126},
			{"Tinh S­¬ng-DiÖt §Õ Ph¸p C«n",136},
			{"Tinh S­¬ng-Ph¸ Lç Tr­îng",151},
			{"NguyÖt KhuyÕt S¸t KiÕp Ph¸p C«n",161},
			{"NguyÖt KhuyÕt Hµo KiÖt Tr­îng",176},
			{"DiÖu D­¬ng Phôc Ma Ph¸p C«n",186},
			{"DiÖu D­¬ng §Þch Kh¸i Tr­îng",201},
			{"Anh Hµo PhËt §µ T¨ng C«n",221},
			{"Anh Hµo Liªn Hoa Tr­îng",236},
			{"Thanh C©u Hæ §Çu Th­¬ng",9},
			{"V©n Léc Kiªn NhÉn Th­¬ng",24},
			{"KÕ NghiÖp B«n L«i Toµn Long th­¬ng",25},
			{"Tö M·ng §Þnh H¶i Th­¬ng",38},
			{"Tö M·ng Dung Kim Th­¬ng",39},
			{"B¹ch Hæ Ngù Phong Th­¬ng",50},
			{"B¹ch Hæ XÝch Minh Th­¬ng",51},
			{"Minh Ph­îng Anh Hïng Th­¬ng",88},
			{"Minh Ph­îng Dôc NhËt Th­¬ng",101},
			{"§»ng Long TÞch §Þa Th­¬ng",114},
			{"§»ng Long Viªm Hoµng Th­¬ng",127},
			{"Tinh S­¬ng-L­u Kim Th­¬ng",139},
			{"Tinh S­¬ng-LuyÖn NhËt Th­¬ng",152},
			{"NguyÖt KhuyÕt Phong Yªn  Th­¬ng",164},
			{"NguyÖt KhuyÕt Tham Lang Th­¬ng",177},
			{"DiÖu D­¬ng KÕ NghiÖp Th­¬ng",189},
			{"DiÖu D­¬ng Ma S¸t Th­¬ng",202},
			{"Anh Hµo Hæ §Çu Th­¬ng",224},
			{"Anh Hµo LÖ ¢m Th­¬ng",237},
		}
	},
	[5] = {
		szName = "Chïy",
		tbEquip = {
			{"Thanh C©u Tö Kim Chïy",18},
			{"V©n Léc Lùc L­îng Chïy",30},
			{"H¸m Thiªn Kim Hoµn §¹i Nh·n ThÇn Chïy",31},
			{"Tö M·ng Sïng Minh Chïy",43},
			{"B¹ch Hæ §Þnh Quang Chïy",60},
			{"Minh Ph­îng ChiÕn ThÇn Chïy",87},
			{"§»ng Long Khai Thiªn ThÇn Chïy",113},
			{"Tinh S­¬ng-Th«n Tµ ThÇn Chïy",138},
			{"NguyÖt KhuyÕt PhÊn Vò ThÇn Chïy",163},
			{"DiÖu D­¬ng H¸m Thiªn ThÇn Chïy",188},
			{"Anh Hµo Tö Kim Chïy",223},
		}
	},
	[6] = {
		szName = "Song §ao",
		tbEquip = {
			{"Thanh C©u BÝch La Uyªn ¦¬ng §ao",15},
			{"V©n Léc Khëi Tó Uyªn ¦¬ng §ao",28},
			{"BÝch H¶i Uyªn ¦¬ng Liªn Hoµn ®ao",29},
			{"Tö M·ng ThÕ H­¬ng Uyªn ¦¬ng §ao",42},
			{"B¹ch Hæ ¶o Th¸i Uyªn ¦¬ng §ao",61},
			{"Minh Ph­îng Ph­¬ng Hoa Song §ao",93},
			{"§»ng Long B¸ch H­¬ng Uyªn ¦¬ng §ao",119},
			{"Tinh S­¬ng-Th¸i VËn Uyªn ¦¬ng §ao",144},
			{"NguyÖt KhuyÕt Phong NguyÖt Uyªn ¦¬ng §ao",169},
			{"DiÖu D­¬ng BÝch H¶i Uyªn ¦¬ng §ao",194},
			{"Anh Hµo BÝch La Uyªn ¦¬ng§ao",229},
		}	
	},
	[7] = {
		szName = "Phi §ao, Phi Tiªu, Tô TiÔn",
		tbEquip = {
			{"B¨ng Hµn §¬n ChØ Phi §ao",19},
			{"Minh Ph­îng LiÔm DiÖm Phi §ao",96},
			{"Minh Ph­îng Thiªn Kiªu Phi Tiªu",98},
			{"§»ng Long Hçn §én Phi §ao",122},
			{"§»ng Long Phong B¹o Phi Tiªu",124},
			{"Tinh S­¬ng-L·nh HuyÕt Phi §ao",147},
			{"Tinh S­¬ng-Truy MÖnh Phi Tiªu",149},
			{"NguyÖt KhuyÕt Th«i MÖnh Phi §ao",172},
			{"NguyÖt KhuyÕt M¹n §å Phi Tiªu",174},
			{"DiÖu D­¬ng B¨ng Hµn Phi §ao",197},
			{"DiÖu D­¬ng S©m Hoang Phi Tiªu",199},
			{"Anh Hµo BÝ Linh Phi §ao",232},
			{"Anh Hµo Phi Tinh Tiªu",234},
			{"Minh Ph­îng Thiªn Hoang Tô TiÔn",97},
			{"§»ng Long ThÝ ThÇn Tô TiÔn",123},
			{"Tinh S­¬ng-Né Liªn Tô TiÔn",148},
			{"NguyÖt KhuyÕt BÝ §éc Tô TiÔn",173},
			{"DiÖu D­¬ng Thiªn Quang Tô TiÔn",198},
			{"Anh Hµo Tµn V©n TIÔn",233},
		}
	},
	[8] = {
		szName = "§ao ThuÉn",
		tbEquip = {
			{"Thanh C©u PhÊn ChiÕn §ao",210},
			{"Thanh C©u TrÝ C«ng ThuÉn",211},
			{"Kim ¤ Ph¸ Tróc §ao",212},
			{"Kim ¤ H¹o Nhiªn ThuÉn",213},
			{"NguyÖt KhuyÕt Hån TrÊn §ao",214},
			{"NguyÖt KhuyÕt Vò Huy ThuÉn",215},
			{"DiÖu D­¬ng PhÇn DiÖm §ao",216},
			{"DiÖu D­¬ng Minh §×nh ThuÉn",217},
			{"Anh Hµo B¸ KhÝ ThuÉn",245},
			{"Anh Hµo Uy Vò §ao",246},
		}
	},
	[9] = {
		szName = "CÇm",
		tbEquip = {
			{"Thanh C©u Chi Cung Kim CÇm",251},
			{"Kim ¤ Chi Tè Ca CÇm",252},
			{"NguyÖt KhuyÕt Chi Nh· Nh¹o CÇm",253},
			{"Anh Hµo Chi Di T¾c CÇm",254},
		}
	},
}
tbNameResHorse = {
	[1] = {
		szName = "Ngùa Th­êng",
		szEquip = {
			{"LiÖt Hoµng M·",0,1},
			{"LiÖt Hoµng M·",0,2},
			{"Hoµng M·",0,3},
			{"Hoµng M·",0,4},
			{"Hoµng Phiªu",0,5},
			{"Hoµng Phiªu",0,6},
			{"§¹i UyÓn Hoµng M·",0,7},
			{"§¹i UyÓn Hoµng M·",0,8},
			{"Phi Hoµng",0,9},
			{"Phi Hoµng",0,10},
			{"LiÖt Thanh M·",1,1},
			{"LiÖt Thanh M·",1,2},
			{"Thanh Th«ng",1,3},
			{"Thanh Th«ng",1,4},
			{"Tö L­u",1,5},
			{"Tö L­u",1,6},
			{"§¹i UyÓn Thanh M·",1,7},
			{"§¹i UyÓn Thanh M·",1,8},
			{"Hoa L­u",1,9},
			{"Hoa L­u",1,10},
			{"LiÖt B¹ch M·",2,1},
			{"LiÖt B¹ch M·",2,2},
			{"B¹ch M·",2,3},
			{"B¹ch M·",2,4},
			{"Ngäc Hoa Th«ng",2,5},
			{"Ngäc Hoa Th«ng",2,6},
			{"§¹i UyÓn B¹ch M·",2,7},
			{"§¹i UyÓn B¹ch M·",2,8},
			{"Tóc S­¬ng",2,9},
			{"Tóc S­¬ng",2,10},
			{"LiÖt H¾c M·",3,1},
			{"LiÖt H¾c M·",3,2},
			{"H¾c M·",3,3},
			{"H¾c M·",3,4},
			{"H¾c Kú",3,5},
			{"H¾c Kú",3,6},
			{"§¹i UyÓn H¾c M·",3,7},
			{"§¹i UyÓn H¾c M·",3,8},
			{"¤ Chïy",3,9},
			{"¤ Chïy",3,10},
			{"LiÖt Hång M·",4,1},
			{"LiÖt Hång M·",4,2},
			{"Hång M·",4,3},
			{"Hång M·",4,4},
			{"Hång Ly",4,5},
			{"Hång Ly",4,6},
			{"§¹i UyÓn H·n HuyÕt M·",4,7},
			{"§¹i UyÓn H·n HuyÕt M·",4,8},
			{"XÝch Ký",4,9},
			{"XÝch Ký",4,10},
			{"¤ V©n §¹p TuyÕt",5,1},
			{"XÝch Thè",5,2},
			{"TuyÖt ¶nh",5,3},
			{"§Ých L«",5,4},
			{"ChiÕu D¹ Ngäc S­ Tö",5,5},
			{"¤ V©n §¹p TuyÕt",5,6},
			{"XÝch Thè",5,7},
			{"TuyÖt ¶nh",5,8},
			{"§Ých L«",5,9},
			{"ChiÕu D¹ Ngäc S­ Tö",5,10},
		}
	},
	[2] = {
		szName = "Ngùa Cao CÊp",
		szEquip = {
			{"B«n Tiªu",6,1},
			{"Phiªn Vò",7,1},
			{"Phi V©n",8,1},
			{"XÝch Long C©u",9,1},
			{"TuyÖt §Þa",10,1},
			{"Du Huy",11,1},
			{"§»ng Vô",12,1},
			{"Siªu Quang",13,1},
			{"Kim Tinh Hæ V­¬ng",14,1},
			{"Háa Tinh Kim Hæ V­¬ng",15,1},
			{"Kim Tinh B¹ch Hæ V­¬ng",16,1},
			{"Long Tinh H¾c Hæ V­¬ng",17,1},
			{"H·n HuyÕt Long C©u",18,1},
			{"Phong V©n B¹ch M·",19,1},
			{"Phong V©n ChiÕn M·",20,1},
			{"Phong V©n ThÇn M·",21,1},
			{"S­ tö",22,1},
			{"L¹c ®µ",23,1},
			{"D­¬ng §µ",24,1},
			{"H­¬u ®èm",25,1},
			{"D­¬ng Sa",26,1},
			{"Ngù Phong",27,1},
			{"Truy ®iÖn",28,1},
			{"L­u Tinh",29,1},
			{"Phiªn Vò",30,1},
			{"XÝch Long C©u",31,1},
			{"Siªu Quang",32,1},
			{"Lam L©n ThÇn Léc",33,1},
			{"Kinh L«i",34,1},
			{"Lõa Hång",35,1},
			{"TuyÕt vùc ChiÕn Lang",36,1},
			{"Ng©n Gi¸p HuyÒn TrÖ",37,1},
			{"ThiÕt KÞ ChiÕn M·",38,1},
			{"HuyÕt VÜ Hå",39,1},
			{"Lôc VÜ Hå",40,1},
			{"HuyÒn Thiªn VÜ Hå",41,1},
			{"TuyÕt vùc ChiÕn Lang",42,1},
			{"TuyÕt vùc ChiÕn M·",43,1},
			{"Tr©u tr¾ng 2 sõng",44,1},
			{"Tr©u tr¾ng 2 sõng cÊp 1",45,1},
			{"Tr©u tr¾ng 2 sõng cÊp 2",46,1},
			{"Tr©u tr¾ng 2 sõng cÊp 3",47,1},
			{"Linh D­¬ng 2 sõng Xanh",48,1},
			{"Hæ tiÒn sö 1",49,1},
			{"Hæ tiÒn sö 2",50,1},
			{"Hæ tiÒn sö 3",51,1},
			{"GÊu Tróc",52,1},
			{"Thá N©u",53,1},
			{"Thá TÝm",54,1},
			{"Thá Hoµng Kim",55,1},
		}
	},
	[3] = {
		szName = "Ngùa KiÕm ThÕ",
		szEquip = {
			{"T¸o Hång",56,10},
			{"Thanh M·",57,10},
			{"§¹i UyÓn",58,10},
			{"¤ Truy",59,10},
			{"¤ V©n §¹p TuyÕt",60,10},
			{"§Ých L«",61,10},
			{"TuyÖt ¶nh",62,10},
			{"ChiÕu D¹ Ngäc S­ Tö",63,10},
			{"H·n HuyÕt B¶o M·",64,10},
			{"XÝch Thè",65,10},
			{"B«n Tiªu",66,10},
			{"Phiªn Vò",67,10},
			{"Hû Hû ",68,10},
			{"Hoan Hoan",69,10},
			{"L¨ng Thiªn",70,10},
			{"Trôc NhËt",71,10},
			{"Hæ C¸t T­êng",72,10},
			{"øc V©n",73,10},
			{"TuyÕt Hån",74,10},
			{"Sø gi¶ Truy Phong",75,10},
			{"Háa Kú L©n",76,10},
			{"L©n Quang",77,10},
			{"L¹c ®µ (Tr¾ng)",78,10},
			{"L¹c ®µ (§en)",79,10},
			{"Kh«ng cã res luotuohuang",80,10},
			{"L¹c §µ Kh«ng B­íu",81,10},
			{"L¹c §µ Kh«ng B­íu (§á)",82,10},
			{"L¹c §µ Kh«ng B­íu (Lôc)",83,10},
			{"B«n L«i",84,10},
			{"Hång Long XÝch DiÖm",85,10},
			{"TuyÖt ThÕ TuyÕt Vò",86,10},
			{"Tóy NguyÖt-V« Tµ",87,10},
			{"Tóy NguyÖt-Trôc Qu©n",88,10},
			{"Thùc NhËt Cuång S­",89,10},
			{"MËt Thµnh ThiÕt Kþ",90,10},
			{"Ngäc Tiªu Dao",91,10},
			{"M¹ch Th­îng Phi S­¬ng",92,10},
			{"TuyÕt Vò Thiªn H­¬ng",93,10},
			{"MÞ Vò Thiªn H­¬ng",94,10},
			{"DuDu Vui VÎ",95,10},
			{"¤ng Thá",96,10},
			{"Kim T­îng Th¸i §¹t",97,10},
			{"Kinh HuyÒn SÊm",98,10},
			{"§éc Vò Thiªn H¹",99,10},
			{"Ng¹o Ng« Hiªn Viªn",100,10},
			{"Nô H«n H¾c ¸m",101,10},
			{"Ngän Löa ¸nh S¸ng",102,10},
			{"Viªm D­¬ng Long Tö",103,10},
			{"L¹c Th¸i Li VÉn",104,10},
			{"T¸i Th¸i TuÕ",105,10},
			{"×ÇÎä°ÁÌì",106,10},
			{"Kh«ng cã res horse72",107,10},
			{"³°·çÓùÉù",108,10},
			{"¾ÅÈð",109,10},
			{"ÈüÌ«Ëê",110,10},
			{"¾ÅÈð",111,10},
			{"Ä°ÉÏº®ÑÌ",112,10},
			{"ÒÀÒÀ¶ÔÓ°",113,10},
			{"Ó¥·É",114,10},
			{"À¶ôá",115,10},
			{"ÑÌ»ª",116,10},
			{"¹Âºè",117,10},
			{"ÐÇÒ«",118,10},
			{"³àÑÒÁéÊÞ",119,10},
			{"Ñ©ÁéÚÐÌý",120,10},
			{"É¬»áÖí",121,10},
			{"ºÉÒ¶Ð¡Öí",122,10},
			{"ÖíÐ¡ºÚ",123,10},
			{"ÉñÎäÐ¡Öí",124,10},
			{"³àÑæâ³õô",125,10},
			{"ÇàÔÆÁé×ð",126,10},
			{"³àÑæâ³õô¡¤Áé",127,10},
			{"ÇàÔÆÁé×ð¡¤»Ã",128,10},
			{"ÒøÔÂÉñÙç",129,10},
			{"Ñ©ºìÙç",130,10},
			{"Ñ©Ä«Ùç",131,10},
			{"ÒøÔÂÉñÙç¡¤Áé",132,10},
			{"Ñ©ºìÙç¡¤Áé",133,10},
			{"Ñ©Ä«Ùç¡¤Áé",134,10},
			{"ÌßÔÆµÄÂ¬",135,10},
			{"Ñ©³áÁ«Óð",136,10},
			{"À¶ì½ÎÚæí",137,10},
			{"È¸ôáÌ¤Ñ©",138,10},
			{"Trïng Res horse117",139,10},
			{"Thá Vµng",140,10},
			{"Thá Hång",141,10},
		}
	},
}
