------------------------------------------------------------------
-- Copyright by Julian-V (https://www.youtube.com/julianv)
------------------------------------------------------------------
tbBoss = { -- tªn boss,id boss, tû lÖ r¬i ®å,series boss,nLevel
    [1] = {
        szName = "TÞnh Th«ng",
        nBossId = 1355,
        nRate = 322,
        nSeries = 0,
        nLevel = 95,
     },
    [2] = {
        szName = "Ng¹o Thiªn T­íng Qu©n",
        nBossId = 1356,
        nRate = 322,
        nSeries = 0,
        nLevel = 95,
    },
    [3] = {
        szName = "LiÔu Thanh Thanh",
        nBossId = 523,
        nRate = 322,
        nSeries = 1,
        nLevel = 95,
     },
    [4] = {
        szName = "T©y V­¬ng Tµ §éc",
        nBossId = 1358,
        nRate = 322,
        nSeries = 1,
        nLevel = 95,
     },
    [5] = {
        szName = "DiÖu Nh­",
        nBossId = 513,
        nRate = 322,
        nSeries = 2,
        nLevel = 95,
     },
    [6] = {
        szName = "Do·n Thanh V©n",
        nBossId = 1360,
        nRate = 322,
        nSeries = 2,
        nLevel = 95,
     },
    [7] = {
        szName = "H¾c Y S¸t Thñ",
        nBossId = 1361,
        nRate = 322,
        nSeries = 3,
        nLevel = 95,
     },
    [8] = {
        szName = "ThËp Ph­¬ng C©u DiÖt",
        nBossId = 1362,
        nRate = 322,
        nSeries = 3,
        nLevel = 95,
    },
    [9] = {
        szName = "Tr­¬ng T«ng ChÝnh",
        nBossId = 511,
        nRate = 322,
        nSeries = 4,
        nLevel = 95,
     },
    [10] = {
        szName = "Thanh Y Tö",
        nBossId = 1364,
        nRate = 322,
        nSeries = 4,
        nLevel = 95,
     },

    [11] = {
        szName = "Cæ B¸ch",
        nBossId = 566,
        nRate = 322,
        nSeries = 0,
        nLevel = 95,
     },
    [12] = {
        szName = "V­¬ng T¸",
        nBossId = 739,
        nRate = 322,
        nSeries = 0,
        nLevel = 95,
     },
    [13] = {
        szName = "HuyÒn Gi¸c §¹i S­",
        nBossId = 740,
        nRate = 322,
        nSeries = 0,
        nLevel = 95,
     },
    [14] = {
        szName = "HuyÒn Nan §¹i S­",
        nBossId = 1365,
        nRate = 342,
        nSeries = 0,
        nLevel = 95,
     },
    [15] = {
        szName = "§­êng BÊt NhiÔm",
        nBossId = 741,
        nRate = 336,
        nSeries = 1,
        nLevel = 95,
     },
    [16] = {
        szName = "§­êng Phi YÕn",
        nBossId = 1366,
        nRate = 342,
        nSeries = 1,
        nLevel = 95,
     },
    [17] = {
        szName = "B¹ch Doanh Doanh",
        nBossId = 742,
        nRate = 336,
        nSeries = 1,
        nLevel = 95,
     },
    [18] = {
        szName = "Lam Y Y",
        nBossId = 582,
        nRate = 336,
        nSeries = 1,
        nLevel = 95,
     },
    [19] = {
        szName = "Thanh TuyÖt S­ Th¸i",
        nBossId = 743,
        nRate = 341,
        nSeries = 2,
        nLevel = 95,
     },
    [20] = {
        szName = "Hµ Linh Phiªu",
        nBossId = 568,
        nRate = 336,
        nSeries = 2,
        nLevel = 95,
     },
    [21] = {
        szName = "Chung Linh Tó",
        nBossId = 567,
        nRate = 336,
        nSeries = 2,
        nLevel = 95,
     },
    [22] = {
        szName = "Yªn HiÓu Tr¸i",
        nBossId = 744,
        nRate = 336,
        nSeries = 2,
        nLevel = 95,
     },
    [23] = {
        szName = "Hµ Nh©n Ng·",
        nBossId = 745,
        nRate = 321,
        nSeries = 3,
        nLevel = 95,
     },
    [24] = {
        szName = "M¹nh Th­¬ng L­¬ng",
        nBossId = 583,
        nRate = 321,
        nSeries = 3,
        nLevel = 95,
     },
    [25] = {
        szName = "§o¹n Méc DuÖ",
        nBossId = 565,
        nRate = 227,
        nSeries = 3,
        nLevel = 95,
     },
    [26] = {
        szName = "Gia LuËt TÞ Ly",
        nBossId = 563,
        nRate = 227,
        nSeries = 3,
        nLevel = 95,
     },
    [27] = {
        szName = "Hµn M«ng",
        nBossId = 748,
        nRate = 341,
        nSeries = 3,
        nLevel = 95,
     },
    [28] = {
        szName = "§¬n Tö Nam",
        nBossId = 746,
        nRate = 341,
        nSeries = 4,
        nLevel = 95,
     },
    [29] = {
        szName = "§¹o Thanh Ch©n Nh©n",
        nBossId = 562,
        nRate = 341,
        nSeries = 4,
        nLevel = 95,
    },
    [30] = {
        szName = "Tõ §¹i Nh¹c",
        nBossId = 1367,
        nRate = 342,
        nSeries = 4,
        nLevel = 95,
     },
    [31] = {
        szName = "Thanh Liªn Tö",
        nBossId = 1368,
        nRate = 875,
        nSeries = 4,
        nLevel = 95,
     },
    [32] = {
        szName = "TuyÒn C¬ Tö",
        nBossId = 747,
        nRate = 341,
        nSeries = 4,
        nLevel = 95,
     },
}
tbFactionBoss = { -- tªn boss,id boss, tû lÖ r¬i ®å,series boss,nLevel
    [1] = {
        szName = "ThiÕu L©m Hé Tù Vâ T¨ng",
        nBossId = 1194,
        nRate = 300,
        nSeries = 0,
        nLevel = 95,
    },
    [2] = {
        szName = "Thiªn V­¬ng TrÊn Bang Hé VÖ",
        nBossId = 1193,
        nRate = 300,
        nSeries = 4,
        nLevel = 95,
    },
    [3] = {
        szName = "D­¬ng Gia Trang HiÖp Kh¸ch",
        nBossId = 1195,
        nRate = 300,
        nSeries = 3,
        nLevel = 95,
    },
    [4] = {
        szName = "Ngò §éc V« S¾c La S¸t",
        nBossId = 1196,
        nRate = 300,
        nSeries = 1,
        nLevel = 95,
    },
    [5] = {
        szName = "Nga Mi Kim §Ønh S­ Th¸i",
        nBossId = 1197,
        nRate = 300,
        nSeries = 2,
        nLevel = 95,
    },
    [6] = {
        szName = "Thóy Yªn M«n V« ¶nh S¸t Thñ",
        nBossId = 1198,
        nRate = 300,
        nSeries = 2,
        nLevel = 95,
    },
    [7] = {
        szName = "C¸i Bang Tiªu Dao ThÇn C¸i",
        nBossId = 1199,
        nRate = 300,
        nSeries = 3,
        nLevel = 95,
    },
    [8] = {
        szName = "Thiªn NhÉn Hé Gi¸o Th¸nh Sø",
        nBossId = 1200,
        nRate = 300,
        nSeries = 3,
        nLevel = 95,
    },
    [9] = {
        szName = "Vâ §ang Th¸i Êt Ch©n Qu©n",
        nBossId = 1201,
        nRate = 300,
        nSeries = 4,
        nLevel = 95,
    },
    [10] = {
        szName = "C«n L«n Hé Ph¸i Thiªn Qu©n",
        nBossId = 1202,
        nRate = 300,
        nSeries = 4,
        nLevel = 95,
    },
    [11] = {
        szName = "Hoa S¬n §éc C« KiÕm Tiªn",
        nBossId = 1231,
        nRate = 300,
        nSeries = 2,
        nLevel = 95,
    },
}
tbAdvancedBoss = { -- tªn boss,id boss, tû lÖ r¬i ®å,series boss,nLevel
    [1] = {
        szName = "Mé Dung Toµn",
        nBossId = 1875,
        nRate = 300,
        nSeries = 2,
        nLevel = 95,
     },
    [2] = {
        szName = "Kim ThÝ L­îng",
        nBossId = 1874,
        nRate = 300,
        nSeries = 0,
        nLevel = 95,
     },
    [3] = {
        szName = "Tr­¬ng Tuyªn",
        nBossId = 1873,
        nRate = 300,
        nSeries = 3,
        nLevel = 95,
     },
}
