AddCommand("Ctrl+`", "", "RequestScriptTable([[sevencity_war]])")
AddCommand("LButton", "", "Mouse_Action()")
AddCommand("RButton", "", "Mouse_Force1()")
AddCommand("Shift+LButton", "", "Mouse_Force0()")
AddCommand("Shift+RButton", "", "Mouse_Force1()")
AddCommand("Ctrl+LButton", "", "Mouse_Say()")
AddCommand("Ctrl+RButton", "", "Mouse_Menu()")
AddCommand("Alt+LButton", "", "Mouse_PartnerAction()")
AddCommand("Alt+RButton", "", "Mouse_Emote_Menu()")
AddCommand("Alt+X", "exit", "ExitGame()")
AddCommand("Alt+Q", "quit", "Exit()")
AddCommand("F1", "", "Open([[help]])")
AddCommand("F12", "", "Open([[NewTask]])")
AddCommand("", "Help", "Open([[help]])")
AddCommand("", "Gióp ®ì", "Open([[help]])")
AddCommand("", "bz", "Open([[help]])")
AddCommand("Esc", "", "Open([[system]])")
AddCommand("Ctrl+N", "", "Open([[options]])")
AddCommand("N", "", "Open([[options]])")
AddCommand("Ctrl+W", "", "Open([[status]])")
AddCommand("W", "", "Open([[status]])")
AddCommand("Ctrl+Q", "", "Open([[items]])")
AddCommand("Q", "", "Open([[items]])")
AddCommand("Ctrl+E", "", "Open([[skills]])")
AddCommand("E", "", "Open([[skills]])")

AddCommand("Ctrl+R", "", "Replay([[rec]])")
AddCommand("R", "", "Open([[friend]])")

AddCommand("Ctrl+S", "", "Replay([[endrec]])")
AddCommand("Ctrl+P", "", "Replay([[pauserec]])")
AddCommand("", "", "Replay([[play]])")
AddCommand("", "", "Replay([[stop]])")
AddCommand("", "", "Replay([[pause]])")
AddCommand("", "", "Replay([[speedup]])")
AddCommand("", "", "Replay([[slowdown]])")

AddCommand("F7", "", "Switch([[showplayername]])")
AddCommand("F8", "", "Switch([[showplayerlife]])")
AddCommand("Ctrl+H", "", "Switch([[pk]])")
AddCommand("Ctrl+D", "", "Open([[tasknote]])")
AddCommand("D", "", "Open([[tasknote]])")
AddCommand("Ctrl+C", "", "Switch([[trade]])")
AddCommand("O", "", "Switch([[trade]])")
AddCommand("Ctrl+V", "", "Open([[map]])")
AddCommand("V", "", "Open([[map]])")
AddCommand("CTRL+K", "", "SwitchChannel()")
AddCommand("K", "", "SwitchChannel()")
AddCommand("Ctrl+Z", "", "Open([[newsmessage]])")
AddCommand("Insert", "", "SwitchPrivateMsgMode()")
AddCommand("Y", "", "Open([[Chara]])")
--AddCommand("U", "", "Open([[Item]])")
AddCommand("I", "", "Open([[Skill]])")
AddCommand("L", "", "Open([[Talk]])")
AddCommand("F", "", "Open([[Attack]])")
AddCommand("G", "", "Open([[Follow]])")
AddCommand("B", "", "Open([[Call]])")
AddCommand("N", "", "Open([[Select]])")
AddCommand("Alt+C", "", "Open([[ChatRoomList]])")
AddCommand("Ctrl+T", "", "Open([[Tong]])")

AddCommand("Enter", "", "Focus([[commandline]])")
AddCommand("Del", "", "ClearMessage()")
AddCommand("PrintScreen", "", "PrintScreen()")
AddCommand("P", "", "Open([[team]])")
AddCommand("", "team", "Open([[team]])")
AddCommand("", "§éi ngò ", "Open([[team]])")
AddCommand("", "dw", "Open([[team]])")
AddCommand("F2", "", "DirectShortcutSkill(0)")
AddCommand("F3", "", "DirectShortcutSkill(1)")
AddCommand("F4", "", "DirectShortcutSkill(2)")
AddCommand("F5", "", "DirectShortcutSkill(3)")
AddCommand("F6", "", "DirectShortcutSkill(4)")
--AddCommand("F7", "", "DirectShortcutSkill(5)")
--AddCommand("F8", "", "DirectShortcutSkill(6)")
AddCommand("F9", "", "DirectShortcutSkill(7)")
AddCommand("F10", "", "DirectShortcutSkill(8)")
AddCommand("F11", "", "Open([[tasknote]])")
AddCommand("F12", "", "Open([[NewTask]])")
AddCommand("`", "", "Open([[battlereport]])")
AddCommand("", "", "Open([[battlestart]])")
AddCommand("", "", "Open([[battlerecord]])")
AddCommand("", "", "Open([[battlerank]])")
AddCommand("1", "", "ShortcutUseItem(0)")
AddCommand("2", "", "ShortcutUseItem(1)")
AddCommand("3", "", "ShortcutUseItem(2)")
AddCommand("4", "", "ShortcutUseItem(3)")
AddCommand("5", "", "ShortcutUseItem(4)")
AddCommand("6", "", "ShortcutUseItem(5)")
AddCommand("7", "", "ShortcutUseItem(6)")
AddCommand("8", "", "ShortcutUseItem(7)")
AddCommand("9", "", "ShortcutUseItem(8)")

AddCommand("M", "", "Switch([[horse]])")
AddCommand("Alt+0", "", "SayPhrase(0)")
AddCommand("Alt+1", "", "SayPhrase(1)")
AddCommand("Alt+2", "", "SayPhrase(2)")
AddCommand("Alt+3", "", "SayPhrase(3)")
AddCommand("Alt+4", "", "SayPhrase(4)")
AddCommand("Alt+5", "", "SayPhrase(5)")
AddCommand("Alt+6", "", "SayPhrase(6)")
AddCommand("Alt+7", "", "SayPhrase(7)")
AddCommand("Alt+8", "", "SayPhrase(8)")
AddCommand("Alt+9", "", "SayPhrase(9)")
AddCommand("Alt+D", "", "Open([[PlayerNpc]])")
AddCommand("Alt+S", "", "Open([[MissleSame]])")
AddCommand("Alt+F", "", "Open([[VisiblePlayer]])")
AddCommand("Alt+Enter", "", "Open([[FullScreen]])")

AddCommand("", "3d", "Set3D(1)")
AddCommand("", "2d", "Set3D(0)")
AddCommand("", "fullwindow", "SetFullWindow(1)")
AddCommand("", "window", "SetFullWindow(0)")
AddCommand("+", "", "Zoom([[in]])")
AddCommand("=", "", "Zoom([[in]])")
AddCommand("-", "", "Zoom([[out]])")


RegisterFunctionAlias("join", "JoinTeam")
RegisterFunctionAlias("Gia nhËp. ", "JoinTeam")
RegisterFunctionAlias("jr", "JoinTeam")
RegisterFunctionAlias("+", "JoinTeam")
RegisterFunctionAlias("trade", "Trade")
RegisterFunctionAlias("Giao dÞch", "Trade")
RegisterFunctionAlias("jy", "Trade")
RegisterFunctionAlias("invite", "InviteTeam")
RegisterFunctionAlias("Mêi", "InviteTeam")
RegisterFunctionAlias("yq", "InviteTeam")
RegisterFunctionAlias("create", "CreateTeam")
RegisterFunctionAlias("Tæ ®éi", "CreateTeam")
RegisterFunctionAlias("zd", "CreateTeam")


SetPhrase(0, "C¸c h¹ ë ®©u?:S")
SetPhrase(1, "Theo t¹i h¹ ®Õn ®©y!:K")
SetPhrase(2, "Mäi ng­êi h·y cïng lªn, thªm ng­êi th× thªm søc!:F")
SetPhrase(3, "Nguy hiÓm, ch¹y lÑ!:$")
SetPhrase(4, "Gióp t¹i h¹ t¨ng m¸u nhanh ®i!:M")
SetPhrase(5, "Cã ai lËp tæ ®éi kh«ng? T¹i h¹ ®ang c« ®¬n qu¸!^o^")
SetPhrase(6, "Bµ con c« b¸c ¬i, hµng nãng hæi ®©y!.:E")
SetPhrase(7, "C¸c h¹ lµ ng­êi ë ®©u, cÊp bao nhiªu råi?:o")
SetPhrase(8, "Huhu, c¸c huynh tû cho ®Ö xin Ýt tiÒn ®i!:) ")
SetPhrase(9, "T¹i h¹ lµ ng­êi míi, xin c¸c huynh tû chiÕu cè!:I")

RegisterFunctionAlias("88", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "7")
RegisterFunctionAlias("an", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "34")
RegisterFunctionAlias("bf", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "103")
RegisterFunctionAlias("ca", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "82")
RegisterFunctionAlias("dd", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "48")
RegisterFunctionAlias("gf", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "105")
RegisterFunctionAlias("gg", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "47")
RegisterFunctionAlias("hi", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "8")
RegisterFunctionAlias("jj", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "42")
RegisterFunctionAlias("jx", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "39")
RegisterFunctionAlias("lv", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "50")
RegisterFunctionAlias("mm", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "43")
RegisterFunctionAlias("ok", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "87")
RegisterFunctionAlias("pk", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "36")
RegisterFunctionAlias("beg", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "9")
RegisterFunctionAlias("bow", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "1")
RegisterFunctionAlias("bug", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "55")
RegisterFunctionAlias("bye", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "5")
RegisterFunctionAlias("cry", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "17")
RegisterFunctionAlias("cut", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "78")
RegisterFunctionAlias("die", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "41")
RegisterFunctionAlias("esc", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "35")
RegisterFunctionAlias("gao", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "109")
RegisterFunctionAlias("han", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "38")
RegisterFunctionAlias("hmm", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "100")
RegisterFunctionAlias("hua", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "63")
RegisterFunctionAlias("hug", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "79")
RegisterFunctionAlias("inn", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "102")
RegisterFunctionAlias("lun", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "57")
RegisterFunctionAlias("nod", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "52")
RegisterFunctionAlias("pat", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "27")
RegisterFunctionAlias("pen", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "66")
RegisterFunctionAlias("tan", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "11")
RegisterFunctionAlias("thx", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "86")
RegisterFunctionAlias("wen", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "44")
RegisterFunctionAlias("zzz", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "88")
RegisterFunctionAlias("18mo", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "28")
RegisterFunctionAlias("aisi", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "117")
RegisterFunctionAlias("aiyi", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "26")
RegisterFunctionAlias("buxx", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "32")
RegisterFunctionAlias("chou", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "108")
RegisterFunctionAlias("gone", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "101")
RegisterFunctionAlias("haha", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "6")
RegisterFunctionAlias("hero", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "98")
RegisterFunctionAlias("idle", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "70")
RegisterFunctionAlias("jiar", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "37")
RegisterFunctionAlias("jidu", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "15")
RegisterFunctionAlias("joke", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "45")
RegisterFunctionAlias("jump", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "72")
RegisterFunctionAlias("jush", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "104")
RegisterFunctionAlias("kick", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "4")
RegisterFunctionAlias("kill", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "116")
RegisterFunctionAlias("kiss", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "3")
RegisterFunctionAlias("lean", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "2")
RegisterFunctionAlias("lick", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "25")
RegisterFunctionAlias("love", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "118")
RegisterFunctionAlias("mapi", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "94")
RegisterFunctionAlias("miss", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "56")
RegisterFunctionAlias("poke", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "113")
RegisterFunctionAlias("poor", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "67")
RegisterFunctionAlias("puke", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "22")
RegisterFunctionAlias("qiao", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "30")
RegisterFunctionAlias("reny", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "123")
RegisterFunctionAlias("rose", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "21")
RegisterFunctionAlias("shiw", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "122")
RegisterFunctionAlias("sigh", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "23")
RegisterFunctionAlias("sing", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "121")
RegisterFunctionAlias("slap", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "12")
RegisterFunctionAlias("spit", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "14")
RegisterFunctionAlias("taoy", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "81")
RegisterFunctionAlias("wink", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "62")
RegisterFunctionAlias("wosh", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "10")
RegisterFunctionAlias("wuwu", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "119")
RegisterFunctionAlias("ysis", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "89")
RegisterFunctionAlias("zany", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "75")
RegisterFunctionAlias("zhen", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "124")
RegisterFunctionAlias("agree", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "92")
RegisterFunctionAlias("baoch", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "65")
RegisterFunctionAlias("baohu", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "53")
RegisterFunctionAlias("bihua", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "51")
RegisterFunctionAlias("blush", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "97")
RegisterFunctionAlias("chuqi", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "74")
RegisterFunctionAlias("crazy", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "84")
RegisterFunctionAlias("dadao", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "31")
RegisterFunctionAlias("dagun", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "106")
RegisterFunctionAlias("dajie", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "91")
RegisterFunctionAlias("daxia", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "58")
RegisterFunctionAlias("doubt", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "33")
RegisterFunctionAlias("drink", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "83")
RegisterFunctionAlias("duish", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "59")
RegisterFunctionAlias("dunno", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "110")
RegisterFunctionAlias("duobu", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "115")
RegisterFunctionAlias("fadai", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "24")
RegisterFunctionAlias("faint", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "29")
RegisterFunctionAlias("fangq", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "76")
RegisterFunctionAlias("gaosh", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "111")
RegisterFunctionAlias("gongx", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "69")
RegisterFunctionAlias("happy", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "68")
RegisterFunctionAlias("hengx", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "80")
RegisterFunctionAlias("jingy", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "93")
RegisterFunctionAlias("kaolv", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "114")
RegisterFunctionAlias("laugh", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "46")
RegisterFunctionAlias("lover", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "60")
RegisterFunctionAlias("marry", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "90")
RegisterFunctionAlias("match", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "54")
RegisterFunctionAlias("meinv", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "96")
RegisterFunctionAlias("paima", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "120")
RegisterFunctionAlias("peace", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "71")
RegisterFunctionAlias("point", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "40")
RegisterFunctionAlias("polan", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "112")
RegisterFunctionAlias("shuai", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "49")
RegisterFunctionAlias("sleep", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "13")
RegisterFunctionAlias("smell", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "19")
RegisterFunctionAlias("smile", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "0")
RegisterFunctionAlias("sorry", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "16")
RegisterFunctionAlias("stuff", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "20")
RegisterFunctionAlias("swear", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "107")
RegisterFunctionAlias("thank", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "85")
RegisterFunctionAlias("visit", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "95")
RegisterFunctionAlias("wanfu", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "99")
RegisterFunctionAlias("wangy", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "64")
RegisterFunctionAlias("weiqu", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "73")
RegisterFunctionAlias("wuchi", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "18")
RegisterFunctionAlias("xiaox", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "77")
RegisterFunctionAlias("xiezi", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "125")
RegisterFunctionAlias("zhich", "SayEmote", 3, "GetRecentPlayerName()", "GetCurrentChannelName()", "61")
